name: datamuse
version: 0.2.0
description: Datamuse API client for Dart/Flutter provides word-finding query engine.
homepage: https://github.com/vaetas/datamuse

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
