name: datamuse
version: 0.2.0
description: Datamuse API client for Dart/Flutter provides word-finding query engine.
homepage: https://github.com/vaetas/datamuse

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  pedantic: ^1.11.1
  dio: ^4.0.0
  json_annotation: ^4.1.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^5.0.2